frr version 8.4_git
frr defaults traditional
hostname frr
service integrated-vtysh-config
no ipv6 forwarding

interface eth0
 ip ospf area 1
 ip ospf network point-to-point
 ip ospf cost 10
exit

interface eth1
 ip ospf area 1
 ip ospf network point-to-point
 ip ospf cost 5
exit

router ospf
 ospf router-id 1.1.1.1
exit
