frr version 10.0
hostname r4
service integrated-vtysh-config

interface eth0
 ip address 10.1.0.2/29
 ip ospf area 1

interface eth1
 ip address 10.1.0.5/29
 ip ospf area 1

interface eth2
 ip address 10.1.0.9/29
 ip ospf area 1

interface eth3
 ip address 192.168.10.2/24
 ip ospf passive

router ospf
 ospf router-id 4.4.4.4
 network 10.1.0.0/24 area 1
 network 192.168.10.0/24 area 1
 passive-interface eth3

line vty