frr version 8.4_git
frr defaults traditional
hostname 1ced1e1be513
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip ospf network point-to-point
exit
!
interface eth1
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 4.4.4.4
 network 0.0.0.0/0 area 0
exit
!
