frr version 8.4_git
frr defaults traditional
hostname d0dd02db8ce5
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 6.6.6.6
 network 0.0.0.0/0 area 0
exit
!
