frr version 8.4_git
frr defaults traditional
hostname frr
service integrated-vtysh-config
no ipv6 forwarding

interface eth0
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 15
exit

interface eth1
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 8
exit

interface eth2
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 10
exit

interface eth3
 ip ospf area 0
 ip ospf network point-to-point
 ip ospf cost 25
exit

router ospf
 ospf router-id 3.3.3.3
exit
