frr version 8.4_git
frr defaults traditional
hostname frr
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip ospf area 2
 ip ospf cost 15
 ip ospf network point-to-point
exit
!
interface eth1
 ip ospf area 2
 ip ospf cost 5
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 6.6.6.6
exit
!