frr version 10.0
hostname r10
service integrated-vtysh-config

interface eth0
 ip address 10.2.0.10/30
 ip ospf area 2

interface eth1
 ip address 10.2.0.14/30
 ip ospf area 2

router ospf
 ospf router-id 10.10.10.10

line vty