frr version 8.4_git
frr defaults traditional
hostname 2463bde3233e
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip ospf network point-to-point
exit
!
interface eth1
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 7.7.7.7
 network 0.0.0.0/0 area 0
exit
!
