frr version 10.0
hostname r7
service integrated-vtysh-config

interface eth0
 ip address 10.0.0.22/30
 ip ospf area 0

interface eth1
 ip address 10.0.0.25/30
 ip ospf area 0

interface eth2
 ip address 10.2.0.1/30
 ip ospf area 2

router ospf
 ospf router-id 7.7.7.7

line vty