frr version 10.0
hostname r12
service integrated-vtysh-config

interface eth0
 ip address 10.0.0.6/30
 ip ospf area 0

interface eth1
 ip address 10.0.0.17/30
 ip ospf area 0

interface eth2
 ip address 10.0.0.30/30
 ip ospf area 0

router ospf
 ospf router-id 12.12.12.12

line vty