frr version 8.4_git
frr defaults traditional
hostname df6fc2ecfc35
no ipv6 forwarding
service integrated-vtysh-config
!
interface eth0
 ip ospf network point-to-point
exit
!
interface eth1
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 5.5.5.5
 network 0.0.0.0/0 area 0
exit
!
