frr version 10.0
hostname r8
service integrated-vtysh-config

interface eth0
 ip address 10.2.0.2/29
 ip ospf area 2

interface eth1
 ip address 10.2.0.5/29
 ip ospf area 2

interface eth2
 ip address 10.2.0.9/29
 ip ospf area 2

interface eth3
 ip address 192.168.20.2/24
 ip ospf passive

router ospf
 ospf router-id 8.8.8.8
 network 10.2.0.0/24 area 2
 network 192.168.20.0/24 area 2
 passive-interface eth3

line vty