frr version 10.0
hostname r11
service integrated-vtysh-config

interface eth0
 ip address 10.0.0.14/30
 ip ospf area 0

interface eth1
 ip address 10.0.0.26/30
 ip ospf area 0

interface eth2
 ip address 10.0.0.29/30
 ip ospf area 0

router ospf
 ospf router-id 11.11.11.11

line vty