frr version 8.4_git
frr defaults traditional
hostname 08282ad15bee
no ipv6 forwarding
service integrated-vtysh-config
!
router ospf
 ospf router-id 1.1.1.1
 network 172.18.0.0/16 area 0
 network 172.20.0.0/16 area 0
exit
!
