frr version 8.4_git
frr defaults traditional
hostname 1a04f9fd5672
no ipv6 forwarding
hostname frr
service integrated-vtysh-config
!
interface eth0
 ip ospf area 1
 ip ospf cost 20
 ip ospf network point-to-point
exit
!
interface eth1
 ip ospf area 0
 ip ospf cost 15
 ip ospf network point-to-point
exit
!
interface eth2
 ip ospf area 1
 ip ospf cost 10
 ip ospf network point-to-point
exit
!
router ospf
 ospf router-id 2.2.2.2
exit
!
